### ISSUE TITLE
component title, item title and menu-item title font too small on small screen

### ISSUE THREAD

**Issue by samumist** [taylortom/adapt-theme-community#3]
The theme's `@component-title-font-size` is set to at 24px which makes it too small for certain title size too small on small screen with this media query:

``` less
.item-title {
    font-size: @item-title-font-size;
    font-weight: @item-title-font-weight;
    line-height: @item-title-line-height;

    @media all and (max-width: @device-width-small) {
        font-size: (@component-title-font-size - 15px);
    }
}
```

![menu-item-title](https://cloud.githubusercontent.com/assets/3883086/18265755/dc4e1286-7449-11e6-97a7-f49e83c5ccb1.png)
![component-title](https://cloud.githubusercontent.com/assets/3883086/18265760/e26b3ff4-7449-11e6-8318-d7d53bd3eefb.png)
![item-title](https://cloud.githubusercontent.com/assets/3883086/18265763/e53a4eaa-7449-11e6-95e8-0665a520649f.png)
